sudo: false

language: node_js
node_js:
  - "10"
  - "12"

os:
  - linux
  - osx

env:
  matrix:
    - NIM_VERSION=1.0.6

before_install:
  - rm -rf ~/.nim

install:
  - node --version
  - npm --version
  - npm install -g nim@$NIM_VERSION
  - npm install

script:
  - npm test
